knative-extensions/knobots

- repos.yaml
Signed-off-by: Ville Aikas <vaikas@vmware.com>
Fetched the list of missing eventing-* repos from here:
https://api.github.com/orgs/knative-sandbox/repos
Reorganized the repos alphabetically, pull out the discovery into its own thing.
> add missing event-* repos

- .github/workflows/update-nightlies.yaml
In conjunction with https://github.com/knative/serving/pull/10028.
> Move net-istio to its own folder for consistency.

- actions-exclude.yaml
- deps-exclude.yaml
- prettier-exclude.yaml
- repos.yaml
The knative-automation account doesn't pass the EasyCLA check.
/kind removal
> Remove tektoncd repos from receiving automated PRs

- repos.yaml
- :broom: Disable notifications of google/knative-gcp PRs to #knative-gcp
/kind cleanup
> Disable notifications to knative-gcp channel

- .github/workflows/auto-updates.yaml
- .github/workflows/update-nightlies.yaml
Depends on: https://github.com/knative-sandbox/knobots/pull/32 (merged 32 first)
This will include the following message when bumping nightlies
```
bumping knative.dev/net-certmanager 859a9fd...af85fbf:
> af85fbf upgrade to latest dependencies (# 164)
> 33225eb Update common github actions (# 163)
> d4e4184 upgrade to latest dependencies (# 161)
> 24aa84b Update common github actions (# 162)
> 894db68 Update common github actions (# 160)
> 225e3b2 upgrade to latest dependencies (# 159)
> b5de400 upgrade to latest dependencies (# 158)
> 331d448 upgrade to latest dependencies (# 157)
```
> Include a log when bumping nightlies

- .github/workflows/auto-updates.yaml
As per title, this fixes the branch behavior of the action and simplifies it a bit too.
The issue before was that the `set-output` call was on the wrong scope, so this changes that. The `required` attribute needs to go too to be able to run this against main/master manually. Finally, the top-level branch prop is now unused, so dropping that.
/assign @mattmoor
> Fix and simplify branch defaulting behavior

- repos.yaml
Repo maintainers already get notified by being assigned.
/kind removal
```release-note
NONE
```
/assign @mattmoor
> Don't notify #ggcr or #ko Slack channels

- .github/workflows/auto-fork.yaml
This PR should fix the following error in `auto-fork` action.
https://github.com/knative-sandbox/knobots/runs/1986629761?check_suite_focus=true
```bash
Run go get knative.dev/test-infra/buoy@master
go get knative.dev/test-infra/buoy@master
shell: /bin/bash -e {0}
env:
GOROOT: /opt/hostedtoolcache/go/1.15.8/x64
go: cannot use path@version syntax in GOPATH mode
Error: Process completed with exit code 1.
```
- :bug: Fix go get in auto-fork action
/kind bug
/cc @n3wscott
> Fix go get in auto-fork action

- .github/workflows/auto-updates.yaml
/assign @n3wscott @lionelvillard @markusthoemmes @evankanderson 
/hold
I'm putting a HOLD on this because docs and operator have not yet cut and merging this will start to float PKG forward, which we don't want.
> Switch knobots to 0.22 for next release

- actions-exclude.yaml
cc @jonjohnsonjr
ggcr runs a different matrix of Go versions since https://github.com/google/go-containerregistry/pull/945, and we'd like to avoid PRs like https://github.com/google/go-containerregistry/pull/947
> Exclude go-containerregistry from actions sync

- .github/workflows/auto-updates.yaml
- actions-omitted.yaml
Right now, `action-sync` syncs all the actions into every repo. But not all actions
apply to all repos (for example, `go build` probably shouldn't apply to `website`, `docs`,
or `community`).
Adds an opt-out mechanism which removes unwanted actions files before creating the PR.
I'm not sure how to test this easily.
> Allow opt-out of syncing certain actions

- .github/workflows/auto-updates.yaml
Fixes e.g. https://github.com/knative-sandbox/knobots/runs/2162366471?check_suite_focus=true
```
mkdir -p "${GITHUB_WORKSPACE}/main/.github/workflows/"
cp $(find "${GITHUB_WORKSPACE}/meta/workflow-templates" -type f -name '*.yaml') \
"${GITHUB_WORKSPACE}/main/.github/workflows/"
yaml2json < "${GITHUB_WORKSPACE}/meta/actions-omitted.yaml" | \
jq -r "(.[\"knative-sandbox/knative-sandbox/reconciler-test\"] // {\"omit\": []}).omit[] + \"*\"" | \
while read GLOB; do rm "${GITHUB_WORKSPACE}/main/.github/workflows/${GLOB}"; done
/home/runner/work/_temp/5ca7e53d-ddcd-4458-a74b-b09ac4061add.sh: line 4: /home/runner/work/knobots/knobots/meta/actions-omitted.yaml: No such file or directory
Error: Process completed with exit code 1.
```
It turns out that the `actions-omitted.yaml` file is in the …
> Add the knobots repo for configuration

- .github/workflows/auto-updates.yaml
Fixes https://github.com/knative-sandbox/knobots/runs/2170334340?check_suite_focus=true
```
mkdir -p "${GITHUB_WORKSPACE}/main/.github/workflows/"
cp $(find "${GITHUB_WORKSPACE}/meta/workflow-templates" -type f -name '*.yaml') \
"${GITHUB_WORKSPACE}/main/.github/workflows/"
yaml2json < "${GITHUB_WORKSPACE}/config/actions-omitted.yaml" | \
jq -r "(.[\"knative/knative/caching\"] // {\"omit\": []}).omit[] + \"*\"" | \
while read GLOB; do rm "${GITHUB_WORKSPACE}/main/.github/workflows/${GLOB}"; done
/home/runner/work/_temp/60170734-7668-498a-9d40-be001d128480.sh: line 4: yaml2json: command not found
Error: Process completed with exit code 127.
```
I wish I knew a better way to test this, sorry for all the spam!
> Load yaml2json before calling it

- .github/workflows/auto-updates.yaml
- community-exclude.yaml
Sync files from knative/community, starting with (generated) OWNERS_ALIASES. Attempt 
to only apply this to knative (and knative-sandbox, if we choose to use 
OWNERS_ALIASES there).
This is an alternate attempt to CODEOWNERS to automate group management, particularly for release leads.
Not sure how to test this...
/kind enhancement
/hold
Need https://github.com/knative/community/pull/532 submitted first.
> Add sync of files from knative/community

- .github/workflows/auto-updates.yaml
This PR should fix the following error:
https://github.com/knative-sandbox/knobots/runs/2198328771?check_suite_focus=true#step:6:10
PR target path should be the same as checkout one.
```
- name: Check out code onto GOPATH
uses: actions/checkout@v2
with:
path: main
repository: ${{ matrix.name }}
```
- :bug: Fix repo path in update-community action that is used to create PR
/cc @evankanderson
> Fix repo path in update-community action

- repos.yaml
As per title, this patch adds net-ingressv2 to the repo list
to kick auto deps update.
/cc @ZhiminXiang @tcnghia @markusthoemmes
> Add net-ingressv2 to the repo list

- .github/workflows/auto-updates.yaml
See https://github.com/knative-sandbox/knobots/runs/2280653757?check_suite_focus=true for a case where the standard "deps update" skips sending PRs to finalize the release, because it thinks no files outside of the modules list would change.
```
On branch main
Your branch is up to date with 'origin/main'.
Changes not staged for commit:
(use "git add <file>..." to update what will be committed)
(use "git restore <file>..." to discard changes in working directory)
modified:   go.mod
modified:   go.sum
modified:   vendor/modules.txt
```
> Add a flag to force deps PRs for release

- .github/workflows/auto-updates.yaml
GitHub complained about an error on line 33:
https://github.com/knative-sandbox/knobots/actions/runs/723948091/workflow
Also discovered that `inputs` are stringly-typed, so defaulted the value to "false", rather than "".
Also fixed a mix of single-quotes and apostrophe on line 34.
> Fix #69 syntax errors, simplify

- .github/workflows/auto-updates.yaml
Referencing an unknown property in the GitHub resource seems to silently succeed returning the empty string. I blame javascript.
> Fix `github.events` to `github.event`

- .github/workflows/auto-updates.yaml
As described in https://github.com/knative/release#after-the-release
> Bump release family to 0.23 after 0.22 release

- .github/workflows/update-nightlies.yaml
`net-istio.yaml` in `knative/serving` hasn't been updated in a week and it's not clear why the job is skipping 
I get a diff of 
```diff
- serving.knative.dev/release: "v20210402-153a3ca3"
+ serving.knative.dev/release: "v20210410-018e5a89"
```
> enable verbose logging temporarily for nightly release bump job

- .github/workflows/update-nightlies.yaml
istio nightly wasn't bumped because the nightly jobs failed - so undoing `set -x` 
I also noticed the script exited when `grep` returned no results - which can happen if a release is re-generated and there is a whitespace difference in the yamls 🤷‍♂️
> drop verbose logging and add some pipefail guards

- actions/update-actions/Dockerfile
`actions/update-actions/entrypoint.sh` uses jq command but the container does not install jq.
So it always produces the following error:
e.g. https://github.com/knative-sandbox/knobots/runs/2514621145?check_suite_focus=true (please check in `Apply work`)
```
/entrypoint.sh: line 27: jq: command not found
```
This patch fixes it.
/cc @evankanderson @xtreme-sameer-vohra @n3wscott
> Add jq command to update-actions

- cmd/gen-actions/actions_template.yaml
This patch makes a tiny change which removes unnecessary `$`.
For example please refer to https://github.com/knative-sandbox/net-contour/pull/493.
It has `$` in the `/assign` line.
```
/assign $knative-sandbox/networking-wg-leads
```
/cc @evankanderson @n3wscott @markusthoemmes
> Remove unnecessary `$` in update actions

- .github/workflows/auto-update-actions.yaml
- .github/workflows/auto-update-community.yaml
- .github/workflows/auto-update-deps.yaml
- .github/workflows/auto-update-gofmt.yaml
- .github/workflows/auto-update-markdown.yaml
- .github/workflows/auto-update-misspell.yaml
This is same fix with https://github.com/knative-sandbox/knobots/pull/84
All template has the issue as https://github.com/knative/serving/pull/11338#issue-643804896
```
/assign $knative/serving-writers
```
/cc @evankanderson @n3wscott @markusthoemmes
> Remove extra `$` in all template

- .github/workflows/auto-fork.yaml
- .github/workflows/update-nightlies.yaml
This patch aligns Go version with 1.16 in the workflows.
All repos are using Go 1.16 now.
> Align Go version with 1.16

- actions-exclude.yaml
- deps-exclude.yaml
- gotool-exclude.yaml
- repos.yaml
Since we included the Homebrew repositories in the release process. We should keep at least `OWNERS` file up-to-date, e.g to have current release leads, or WG leads present.
- Add repo `knative/homebrew-client`
- Add repo `knative-sanbox/homebrew-kn-plugins`
- Enable only meaningful actions for the repositories 
/cc @rhuss
> Add client's homebrew repositories

- deps-exclude.yaml
As per title. The respective infra is not there yet and we'll have to figure out the best way to release an interim release to be able to catch up with Knative HEAD and get onto the Knative release-train.
/assign @dsimansk
> Disable kn-plugin-func dependencies

- actions/update-community/entrypoint.sh
This reverts commit f723a9004cbd85cb4585ba303004faae28c11104.
Per the discussion [here](https://github.com/knative/serving/pull/12057#discussion_r718279987), the COC doc in community is not necessarily suitable for all repos, so this PR takes it back out of the automation.
cc @markusthoemmes  @evankanderson
> Revert "adding COC doc for all knative repos (#112)"

- .github/workflows/update-nightlies.yaml
We're not receiving nightly updates for eventing since 12 days ago https://github.com/knative-sandbox/eventing-kafka-broker/tree/main/third_party/eventing-latest
The `eventing-kafka-broker` nightly job was mapped to 2 includes, so GH actions was using only the last one.
- Fix eventing nightly updates for eventing-kafka-broker
/kind bug
> Fix Eventing nightly updates for eventing-kafka-broker

- repos.yaml
Part of completing https://github.com/knative/community/issues/724.
> Rename net-ingressv2 to net-gateway-api

- actions/update-actions/entrypoint.sh
A small mistake I made on the last PR. See https://github.com/knative-sandbox/knobots/runs/3904253361?check_suite_focus=true for the effect (it doesn't see go.mod nor the files)
> Move into repo-to-change before applying gofmt

- actions/calculate-matrix/Dockerfile
- actions/update-deps/Dockerfile
- actions/update-gofmt/Dockerfile
- actions/update-misspell/Dockerfile
We need the dep updates to be 1.17 based too, as well as the gofmt action. Might as well make them all 1.17.
> Move all update actions to 1.17

- actions-omitted.yaml
As quickstart plugin is now on the release train, run the releasability job for it.
> Run releasability for quickstart

- .github/workflows/update-nightlies.yaml
As per title, this patch adds net-gateway-api to update-nightlies.yaml.
> Add net-gateway-api to update-nightlies.yaml

- repos.yaml
The website repo has been archived, so let's remove it from the automation...
> Remove website repo from automation

- .github/workflows/update-nightlies.yaml
The special release label was being used in a webhook selector which was
removed. This diff broke how we calculated the from and to sha's for the
nightly updates
ie. the following diff is what broke the script before
```
-    serving.knative.dev/release: "v20220203-d2a7c418"
+    serving.knative.dev/release: "v20220217-f40f6752"
-    serving.knative.dev/release: "v20220203-d2a7c418"
+    serving.knative.dev/release: "v20220217-f40f6752"
-        - key: serving.knative.dev/release
```
/assign @kvmware
> fix grep expression when figuring out release shas

- repos.yaml
Since both the Delivery and Sources WG don't exist anymore.
> Replace channel-wg-leads and source-wg-leads by eventing-writers

- workflow-templates/knative-releasability.yaml
We moved the workflows that are propagated to all the repos into the `knobots` repo.
We want to bake in the release version in the respective repos - so this PR adds the version as the default.
/hold will discuss with the release leads
> bake next release version into workflow template

- .github/workflows/auto-update-actions.yaml
- .github/workflows/auto-update-community.yaml
- .github/workflows/auto-update-deps.yaml
- .github/workflows/auto-update-gofmt.yaml
- .github/workflows/auto-update-markdown.yaml
- .github/workflows/auto-update-misspell.yaml
- actions/update-actions/action.yaml
- actions/update-actions/entrypoint.sh
- actions/update-community/action.yaml
- actions/update-community/entrypoint.sh
- actions/update-deps/action.yaml
- actions/update-deps/entrypoint.sh
- actions/update-gofmt/action.yaml
- actions/update-gofmt/entrypoint.sh
- actions/update-markdown/action.yaml
- actions/update-markdown/entrypoint.sh
- actions/update-misspell/action.yaml
- actions/update-misspell/entrypoint.sh
- cmd/gen-actions/actions_template.yaml
1. Remove `create_pr` from outputs since all the actions are already using it as an env var. This move is already reflected in the [README](https://github.com/knative-sandbox/knobots/blob/main/README.md) so it looks it just needs some cleanups.
2. Add `skip-review` label to enable auto-merge PRs that update community files. This is part of the work for https://github.com/knative/test-infra/issues/2965. In the future the same config can be extended to other actions as well.
> Enable auto-merge for update-community PRs and small cleanups

- actions/update-community/action.yaml
- actions/update-community/entrypoint.sh
See: https://github.com/knative/community/pull/1008
The move was necessary so TOC can approve peribolos updates
> OWNER_ALIASES in knative/community are in a different location now

- workflow-templates/knative-releasability.yaml
> default inputs on scheduled runs

- workflow-templates/knative-go-test.yaml
This PR brings back the former behavior, when unit tests and Codecov is executed on push to main and release branches.
https://knative.slack.com/archives/CCSNR4FCH/p1649768685403129
- Run knative-go-test action on main branch
/cc @dprotaso
> Run knative-go-test action on main branch

- actions/update-deps/action.yaml
Auto-update haven't floated Knative deps after 1.5 due to missing version bump.
In addition should fix: 
https://github.com/knative-sandbox/knobots/runs/6804629743?check_suite_focus=true
- :broom:  Bump update-deps to next release version
/cc @dprotaso @evankanderson
> Bump update-deps to next release version

- actions-omitted.yaml
The repos that I have marked for omission are not part of the current release train: https://github.com/knative/release/issues/141 and https://github.com/knative/release/blob/main/.github/ISSUE_TEMPLATE/release-checklist.yaml
This has the unintended effect of making the release-1dotX very noisy which isn't helpful.
@knative-sandbox/knative-release-leads 
/cc @evankanderson 
```
REDACTED  MCW0CDP3YY  ~  Desktop  Git  $  gh api repos/knative/serving/releases | jq '.[0] | .name,.created_at' | tr '\n' ' ' && echo
"Knative Serving release v1.6.0" "2022-07-12T20:28:39Z"
REDACTED  MCW0CDP3YY  ~  Desktop  Git  $  gh api repos/knative/test-infra/releases | jq '.[0] | .name,.created_at' | tr '\n' ' ' && echo
null null
REDACTED  MCW0CDP3YY  ~  Desktop  Git  $  gh api …
```
> Remove releasability action from some repos

- .github/workflows/auto-fork.yaml
- .github/workflows/update-nightlies.yaml
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: naveen <172697+naveensrinivasan@users.noreply.github.com>
> chore: Set permissions for GitHub actions

- repos.yaml
Also moves the kn-plugin-func repo to the newly added functions section to keep the two function related repos together.
Signed-off-by: Lance Ball <lball@redhat.com>
> chore: knative-sandbox/func-tastic in repos.yaml

- actions-exclude.yaml
Some of the actions are OK, but others such as `go test` are causing
pull requests to fail. This repo is not a typical golang repo in the
traditional knative sense. It is a set of templates for the `func`
binary and as such does not need most of the regular workflow jobs.
Signed-off-by: Lance Ball <lball@redhat.com>
> chore: remove func-tastic from knative GH actions

- .github/workflows/auto-fork.yaml
`gh` cli GPG key was rotated in https://github.com/cli/cli/issues/617 as it expired. The new method should be more robust.
> Fix `gh` cli gpg key

- actions-omitted.yaml
- deps-exclude.yaml
- repos.yaml
This commit removes the `releasability` workflow exception for kn-plugin-func, and no longer excludes it from the deps workflow.
Incidentally, the Slack channel recently changed, so I have also fixed that reference here.
This is all in preparation for functions to ride the knative release train.
/kind chore
Signed-off-by: Lance Ball <lball@redhat.com>
> chore: add kn-plugin-func to release train

- .github/workflows/auto-update-deps.yaml
Currently `Update Deps and Codegen` is failing as: https://github.com/knative-sandbox/knobots/actions/workflows/auto-update-deps.yaml
This is due to the error `##[error]Validation Failed: {"resource":"Issue","code":"custom","field":"body","message":"body is too long (maximum is 65536 characters)"}` in [log](https://pipelines.actions.githubusercontent.com/serviceHosts/02472a65-baf5-4806-be79-3bf6384a6957/_apis/pipelines/1/runs/6445/signedlogcontent/21?urlExpires=2022-10-12T02%3A04%3A58.7482262Z&urlSigningMethod=HMACV1&urlSignature=enXamonNdb%2FBrwb3UB2k%2FUYPioLwVw6jSaekUa4gsTk%3D).
The body contains the following line and it exceeds the limit.
```
bumping golang.org/x/mod 9b9b3d8...86c51ed:
> 86c51ed all: remove golang.org/x/xerrors dependency
> 41445a1 zip: update …
```
> Drop detail log in PR body

- actions/update-deps/entrypoint.sh
While https://github.com/knative-sandbox/knobots/commit/e19afa3be6e4b46b882b49b3503fc96a71179709 fixes the issue when running the docker image locally, GHAs still fails with the same issue. The included changes were testes using GHAs and passed. I also reverted the previous changes as that did not solve the issue.
- :bug: Fix https://github.com/knative/test-infra/issues/3707
Fixes https://github.com/knative/test-infra/issues/3707
```release-note
```
**Docs**
```docs
```
> Fix unsafe git dir error

- repos.yaml
Signed-off-by: Paul S. Schweigert <paul@paulschweigert.com>
As networking was merged into the serving WG, replacing networking-wg-leads with serving-writers for all repos.
/assign @dprotaso
> Updates assignees for networking repos

- community-exclude.yaml
- repos.yaml
We created knobots when actions was pretty immature - now it's pretty good and  downstream orgs can setup their own workflows and potentially use stuff from `knative/actions`
> drop external orgs

- actions/update-deps/entrypoint.sh
In eventing-istio we use Git submodules to hold
run eventing core tests and auto update deps
failed in https://github.com/knative-sandbox/knobots/actions/runs/4339031748/jobs/7576246142
with: `fatal: detected dubious ownership in repository at`
- Add Git submodules to safe directories similarly to /github/workspace/main
> Add Git submodules to safe directories

- .github/workflows/auto-fork.yaml
- actions/update-deps/Dockerfile
- :broom: Use extracted tools from knative.dev/toolbox
/kind cleanup
Related https://github.com/knative/toolbox/pull/3
Related https://github.com/knative/community/issues/1291
> :broom: Extract tools to knative.dev/toolbox

- .github/workflows/auto-update-actions.yaml
- .github/workflows/auto-update-community.yaml
- .github/workflows/auto-update-deps.yaml
- .github/workflows/auto-update-gofmt.yaml
- .github/workflows/auto-update-markdown.yaml
- .github/workflows/auto-update-misspell.yaml
- .github/workflows/update-nightlies.yaml
- actions/calculate-matrix/entrypoint.sh
- actions/update-actions/entrypoint.sh
- actions/update-community/entrypoint.sh
- actions/update-deps/entrypoint.sh
- actions/update-gofmt/entrypoint.sh
- actions/update-markdown/entrypoint.sh
- actions/update-misspell/entrypoint.sh
- cmd/gen-actions/actions_template.yaml
On some actions (e.g. [run 4374781596](https://github.com/knative-sandbox/knobots/actions/runs/4374781596)), we see the following notice: 
```
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```
This PR addresses it and uses env vars instead.
- :broom: set-output was deprecated and `GITHUB_OUTPUT` env var should be used instead according to
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/.
/kind cleanup
WIP: as I am not sure how to test it
> [WIP]: Switch to `GITHUB_OUTPUT` env var instead of using deprecated `set-output`

- .github/workflows/update-nightlies.yaml
- :broom: Remove job to copy the nightly channel & source CRDs from eventing-kafka to the eventing-kafka-broker repo as the APIs have been migrated.
/kind cleanup
/assign @matzew @pierDipi @aliok
> Remove job to copy eventing-kafka nightlies to eventing-kafka-broker repo

- actions/update-actions/entrypoint.sh
Our action sync didn't delete old repos - so adding it explicitly
I was thinking of removing things with `knative-*` prefix but it looks like some repos have workflows that follow this pattern unfortunately. So I didn't want to delete those by accident
> remove old workflows

- .github/workflows/update-nightlies.yaml
the `module` param actually refers to the module of the nightly release - not the target repo where the release is being updated
> fix module name

- .github/workflows/auto-update-deps.yaml
- actions/update-deps/auto-apply.yaml
- actions/update-deps/entrypoint.sh
This reverts commit a1b9e6bf00de1bc4f2333128559c5b386853a4f6.
This will prevent knobots from creating PRs where the only updates are `go.mod` changes (eg. OWNER file updates)
> Revert "force update deps during release time (#297)"

- actions/update-gofmt/Dockerfile
At some point we should just kill this
> Make go version consistent with actions

- repos.yaml
https://github.com/knative/community/issues/1378
- Remove archived knative-sandbox/control-protocol repository
> Remove archived knative-sandbox/control-protocol repository

- .github/workflows/update-nightlies.yaml
In eventing-istio we need the latest from eventing and eventing-kafka-broker (https://github.com/knative-sandbox/eventing-istio/tree/main/third_party).
Required for https://github.com/knative-sandbox/eventing-istio/pull/29 to get eventtype v1beta2
/assign @pierDipi
> Add job to sync eventing & EKB latest to eventing-istio

- .github/workflows/update-nightlies.yaml
We are seeing the following on some update nightlies PRs:
> @knative-automation: GitHub didn't allow me to request PR reviews from the following users: knative/eventing-wg-leads.
> 
> Note that only [knative-sandbox members](https://github.com/orgs/knative-sandbox/people) and repo collaborators can review this PR, and authors cannot review their own PRs.
For example on https://github.com/knative-sandbox/eventing-istio/pull/31#issuecomment-1598571578. 
This PR uses the knative-sandbox groups for assignees for knative-sandbox projects.
> Use knative-sandbox teams for sandbox repos as assignees

- actions/update-gofmt/entrypoint.sh
changed finding patterns to include vendor and third_party path at all the level instead of root level to exclude these directories by update-gofmt at multimodule go setup.
/kind bug
Fixes #244 #259 
```release-note
NONE
```
> excluding vendor and third_party at all the level in multimodule setup in update-gofmt

- .github/workflows/update-nightlies.yaml
See discussion in https://cloud-native.slack.com/archives/C04LY4M2G49/p1697606859044749
Add `skip-review` label on automated yaml/image bumps to skip reviews on automated bumps of dependant YAML and images, as it makes not much sense to review them manually (these diff are not really reviewable: [changed the image](https://github.com/knative/serving/pull/14532/files#diff-98ca8086b0e104b5818b24a99727ddc62096abfa5b4e1c0f66c42948a4893c80R346))
/assign @dprotaso 
/assign @upodroid
> Add `skip-review` label on automated yaml/image bumps

- actions/update-deps/Dockerfile
Some of the update-deps jobs require helm to be installed (e.g. eventing or eventing-kafka-broker).
See: https://github.com/knative-extensions/knobots/actions/runs/7482975295/job/20367497039 or https://github.com/knative/eventing/blob/bc89d285177775c5e287aea32e86a502eddac80e/hack/update-cert-manager.sh#L14-L17
This PR addresses it and installs the latest helm 3 version into the update-deps image.
> Provide helm in update-deps image

- repos.yaml
Serving doesn't use this framework
> serving-writers shouldn't be tagged to review reconciler-test PRs

- repos.yaml
- :gift: Add func-go to repository config
Per our earlier conversation on #knative-functions channel. In case we want to enable syncing various common bits, inluding GH actions, owners/community files etc. 
The team is already created per: https://github.com/knative/community/blob/main/peribolos/knative-extensions-OWNERS_ALIASES#L116-L121. To leverage the alias in owners.  
We can use exclude lists to drop unnecessary updates as needed for the `func-go`.
/hold
Adding hold for evaluating if it's needed in the repository. 
/cc @matzew @lkingland @matejvasek
> Add func-go to repository config

- repos.yaml
Add this repo back so we restart some automation
Part of https://github.com/knative/eventing/issues/7670
/assign @knative-extensions/eventing-rabbitmq-approvers
> Add eventing-rabbitmq integration back 

- .github/workflows/update-nightlies.yaml
- repos.yaml
- Remove archived knative-extensions/net-certmanager repository
Partially https://github.com/knative/community/issues/1563
> Remove archived knative-extensions/net-certmanager repository

- repos.yaml
- Rm plugin diag and migration repos from config
Per https://github.com/knative/community/pull/1591
/cc @rhuss 
/cc @knative-extensions/productivity-leads
> Rm plugin diag and migration repos from config

- .github/workflows/update-nightlies.yaml
One of the [current update-nightlies jobs](https://github.com/knative-extensions/knobots/actions/runs/10771910994/job/29868428658) fails, as the target directory does not exist yet in the repository. 
```
Run for x in eventing-crds.yaml eventing-core.yaml; do
/home/runner/work/_temp/37d75833-0c7e-49d8-89c7-2673193c8cad.sh: line 2: /home/runner/work/knobots/knobots/./third_party/eventing-latest/eventing-crds.yaml: No such file or directory
Error: Process completed with exit code 1.
```
This PR addresses it and updates the CURL command to create the needed directories if they don't exist.
> Create target dir if it does not exist in update-nightlies

- actions/calculate-matrix/Dockerfile
- actions/update-actions/Dockerfile
- actions/update-deps/Dockerfile
- actions/update-gofmt/Dockerfile
- actions/update-misspell/Dockerfile
Bumps the Go version used in the Dockerfiles  to 1.23 in order to be in sync with https://github.com/knative/actions/tree/main/setup-go
> Bump go version  in Dockerfiles

- .github/workflows/update-nightlies.yaml
Eventing core needs to use manifests from eventing-integrations.
> Add update eventing-integrations manifests for Eventing

- repos.yaml
- Remove deprecated client-pkg repository from config
Not used anymore, therefore we don't need updates machinery to executed on it. 
/cc @dprotaso @cardil @gauron99
> Remove deprecated client-pkg repository from config

- repos.yaml
The failed dep update has been spamming the channel for two weeks and it doesn't seem like anyone is going to fix it at this moment.
Disable it for now
> disable serving progressive rollouts dep bump

- repos.yaml
Follow up on - the prior PR did a separate clean up - https://github.com/knative-extensions/knobots/pull/440
> drop progressive serving rollout repo
