knative-extensions/knobots

- .github/workflows/auto-updates.yaml
- README.md
- repos.yaml
> Drop the pr-notify option.

- .github/workflows/auto-updates.yaml
- Fixes https://github.com/google/knative-gcp/issues/1852
- ignore any genfiles reported in .gitattributes for auto format PRs
> ignore generated files (as reported in .gitattributes) for auto format

- misspell-exclude.yaml
> Exclude eventing-redis from misspell

- repos.yaml
- :broom: Update Knative-gcp notification settings
/kind
> Replace Nacho channel with actual channel

- .github/workflows/auto-updates.yaml
> Fix the ko install

- repos.yaml
Signed-off-by: Francesco Guardiani <francescoguard@gmail.com>
- :gift: Added reconciler-test
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```
> Added reconciler-test to the synced repos

- .github/workflows/auto-updates.yaml
We now include more details about the changes that are pulled in when bumping dependencies automatically
example PR: https://github.com/knative/serving/pull/10520
tool source is here: https://github.com/dprotaso/modlog
> Include specific details about module changes

- .github/workflows/update-nightlies.yaml
> Skip nightly release PR if there are no code changes

- .github/workflows/update-nightlies.yaml
- look for `knative.dev/release` vs. serving specific
- search for the label value and then determine the sha from that
> future proof ref lookup

- repos.yaml
- Add `knative-sandbox/kn-plugin-admin` to repos.yaml
- Add knative-sandbox/kn-plugin-source-kafka to repos.yaml
- Fix channel name `client` -> `cli`
/cc @rhuss @navidshaikh @maximilien
> Add kn-plugin-admin and kn-plugin-source-kafka to config

- .github/workflows/auto-fork.yaml
forky was not forking because of a typo.
fixes https://github.com/knative-sandbox/knobots/issues/51
> fix token string

- repos.yaml
Signed-off-by: Francesco Guardiani <francescoguard@gmail.com>
Added control-protocol repo
> Added control protocol repo

- prettier-exclude.yaml
-
-
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```
> Remove kn-plugin-* for Markdown prettifier PRs

- .github/workflows/auto-updates.yaml
> Ignore spurious misspell complaint

- repos.yaml
- 🎁  🧹  Enable automatic runs/PRs of `hack/update-codegen.sh`, so that `go mod` redirects are automatically created for new repos.
/kind cleanup
> Auto-manage website for update-codegen in particular.

- .github/workflows/update-nightlies.yaml
- Add update nightly config for eventing-kafka-broker
/kind enhancement
> Add update nightly config for eventing-kafka-broker

- repos.yaml
> Add kperf to the repo list

- prettier-exclude.yaml
Hugo shortcodes confuse prettier.
> Skip markdown formatting for website

- .github/workflows/update-nightlies.yaml
There is a syntax error in this workflow: https://github.com/knative-sandbox/knobots/actions/runs/681247519/workflow
> Fix bad indentation

- repos.yaml
- Remove google/exposure-notifications-server from robots repos
/kind cleanup
```release-note
NONE
```
> remove EN server

- actions/update-actions/entrypoint.sh
- actions/update-community/entrypoint.sh
- actions/update-deps/entrypoint.sh
- actions/update-gofmt/entrypoint.sh
- actions/update-markdown/entrypoint.sh
- actions/update-misspell/entrypoint.sh
I'm not sure this is the _right_ way to do it, but I was able to create https://github.com/knative/operator/pull/572 after previously reproducing the same errors that knative-automation was seeing.
Fixes #79
> Fix file permissions in docker actions.

- repos.yaml
> Opt out google/ko and google/go-containerregistry

- actions/update-deps/action.yaml
-
-
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```
> Bump to 0.24

- actions/update-community/action.yaml
- actions/update-community/entrypoint.sh
Pass organization info into `Update-Community`, so it can find the right file.
Add some debugging output.
/kind bug
/assign @n3wscott
> Fix update-community and add logging

- repos.yaml
- :wastebasket: Remove knative-gcp from repos.xml
> remove knative-gcp from update bot

- repos.yaml
- Add [kn-plugin-quickstart](https://github.com/knative-sandbox/kn-plugin-quickstart) to the update bot
> Add kn-plugin-quickstart 

- repos.yaml
- debug net-istio bump
- debug
- drop camel
> drop camel

- actions-exclude.yaml
- deps-exclude.yaml
- gotool-exclude.yaml
- prettier-exclude.yaml
- repos.yaml
- remove go-containerregistry from excludes
- remove google/exposure-notifications-server
- include release-repo
> cleanup some excludes and include knative/release repo

- actions-omitted.yaml
- kperf - drop releasability action
- omit release action on some kn-plugin repos
> omit some repos from release actions

- actions/calculate-matrix/Dockerfile
- actions/update-actions/Dockerfile
- actions/update-deps/Dockerfile
- actions/update-gofmt/Dockerfile
- actions/update-misspell/Dockerfile
See https://github.com/knative/eventing/pull/5636 for an example of the PRs that Go 1.17 creates.
> Not ready to upgrade to Go 1.17 yet

- .github/workflows/update-nightlies.yaml
Signed-off-by: Matthias Wessendorf <mwessend@redhat.com>
- Adding Kafka Channel CRD Download for Broker repo
-
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```
> Adding Kafka Channel CRD Download

- repos.yaml
- :gift: Add client-pkg repository
/cc @rhuss
> Add client-pkg repository

- README.md
Wrote up some documentation on how the different components of knobots fit together as well as why any of this is here.
> Add documentation on Knobots

- actions/update-community/auto-apply.yaml
- actions/update-markdown/auto-apply.yaml
- actions/update-misspell/auto-apply.yaml
Next up: document how the auto-apply files work.
> Fix source auto-apply.yaml shortnames for matrix.

- actions/update-community/entrypoint.sh
- Adding COC doc (from community repo) to the auto-update list
/kind enhancement
Mentioned as part of the [GA work](https://github.com/knative/community/issues/680#issuecomment-926810060)
> Adding COC doc for all knative repos

- actions/update-community/entrypoint.sh
- :bug: fixing typo in community COC Script
/kind bug
/assign @evankanderson
> Fixing typo in coc script

- .github/workflows/update-nightlies.yaml
Part of https://github.com/knative-sandbox/eventing-kafka-broker/issues/312
- Add KafkaSource to eventing-kafka-broker nightly update
/assign @matzew
> Add KafkaSource to eventing-kafka-broker nightly update

- actions/update-actions/Dockerfile
- actions/update-actions/entrypoint.sh
This should solve the chicken/egg issue that can be seen in https://github.com/knative-sandbox/net-kourier/pull/659 for example.
> Reformat Golang code after action update in one PR

- .github/workflows/update-nightlies.yaml
Add nightly builds of eventing to eventing-rabbitmq
> Add nightly builds of eventing CRDs to rabbitmq

- .github/workflows/update-nightlies.yaml
Signed-off-by: Matthias Wessendorf <mwessend@redhat.com>
- as per title
-
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```
> Only download that one KafkaSource CRD

- actions/update-deps/Dockerfile
I'm noticing go get is installing an older buoy for some reason
> use go install

- actions/update-deps/action.yaml
> Update to release 1.2/0.29

- actions/update-deps/action.yaml
> Update deps action to release 1.3/0.30

- repos.yaml
> Knative Sandbox PRs should be assigned to knative-sandbox/productivity

- repos.yaml
-
-
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```
> Fix reconciler-test assignees

- actions-exclude.yaml
- deps-exclude.yaml
- gofmt-exclude.yaml
- markdown-exclude.yaml
- misspell-exclude.yaml
- repos.yaml
> include productivity repos to get OWNER updates

- repos.yaml
> Fix the config for actions and actions-downstream-test repos

- actions-exclude.yaml
- deps-exclude.yaml
- gofmt-exclude.yaml
- markdown-exclude.yaml
- misspell-exclude.yaml
- repos.yaml
Adds infra to repos.yaml to get OWNER updates
> include Infra repo to get OWNER updates

- actions-exclude.yaml
- deps-exclude.yaml
- gofmt-exclude.yaml
- markdown-exclude.yaml
- misspell-exclude.yaml
- repos.yaml
> include Knobots to get OWNER updates

- .github/workflows/auto-update-actions.yaml
- .github/workflows/auto-update-community.yaml
- .github/workflows/auto-update-deps.yaml
- .github/workflows/auto-update-gofmt.yaml
- .github/workflows/auto-update-markdown.yaml
- .github/workflows/auto-update-misspell.yaml
- cmd/gen-actions/actions_template.yaml
Includes fix: https://github.com/peter-evans/create-pull-request/issues/1163
> bump actions

- repos.yaml
This repo has been deprecated.
> Remove eventing-awssqs

- actions/update-deps/action.yaml
change release in update-deps action to next release which is 1.5
/cc @dprotaso @ikvmw
> Update after release 1.4

- actions-exclude.yaml
- deps-exclude.yaml
- gofmt-exclude.yaml
- markdown-exclude.yaml
- misspell-exclude.yaml
- repos.yaml
It's been archived and will be deleted in the future
> drop downstream test repo

- workflow-templates/knative-releasability.yaml
> Update releasability defaults for 1.5

- workflow-templates/knative-releasability.yaml
Signed-off-by: Paul S. Schweigert <paulschw@us.ibm.com>
cc: @evankanderson
> Update releasability defaults for v1.6

- actions/update-deps/action.yaml
- :broom: Post release bump to next version
> Bump update-deps to next release version

- repos.yaml
> Add Security Guard Repo

- actions/update-deps/action.yaml
> bump version to 1.8

- repos.yaml
Signed-off-by: Paul S. Schweigert <paul@paulschweigert.com>
Keeping all the kn plugins in one place
> Move quickstart to cli

- repos.yaml
- :broom: update knobots to point to new `func` repository on `knative` org
/kind cleanup
Fixes 
https://github.com/knative/community/issues/1169
```release-note
```
**Docs**
```docs
```
> [chore] Preparing for func to be moved to knative org

- workflow-templates/knative-releasability.yaml
As per title.
I just referred to https://github.com/knative-sandbox/knobots/pull/224.
/cc @lionelvillard
> Update releasability for 1.8

- .github/workflows/auto-fork.yaml
- actions/calculate-matrix/Dockerfile
- actions/update-actions/Dockerfile
- actions/update-deps/Dockerfile
- actions/update-gofmt/Dockerfile
- actions/update-misspell/Dockerfile
/assign @kvmware @nader-ziada @gabo1208
> bump knobots to go1.19

- actions-omitted.yaml
- repos.yaml
It will be archived
/assign @lionelvillard @pierDipi
> drop knative-sandbox/discovery

- actions-omitted.yaml
- repos.yaml
- Add the async-component to knobots auto updates
Fixes [115](https://github.com/knative-sandbox/async-component/issues/115)
> add knobots automation for async

- actions-omitted.yaml
- repos.yaml
Signed-off-by: jwcesign <jiangwei115@huawei.com>
Part of https://github.com/knative/community/issues/1195
```release-note
none
```
**Docs**
```docs
none
```
> Add Scaling Group Repo

- actions/update-deps/action.yaml
Signed-off-by: Paul S. Schweigert <paul@paulschweigert.com>
Don't merge until the current release is done
/hold
> Update deps for v1.10

- actions/update-deps/entrypoint.sh
Move permission blub up and change the permission for the parent git repo to address new security of git. More info here: https://github.com/git/git/commit/8959555cee7ec045958f9b6dd62e541affb7e7d9
:bug: Fix Update-deps bug https://github.com/knative/test-infra/issues/3707
/kind <kind>
Fixes https://github.com/knative/test-infra/issues/3707
```release-note
```
**Docs**
```docs
```
> Change permission for Parent git dir

- repos.yaml
> Add eventing-istio to repositories

- actions/update-deps/entrypoint.sh
The relative dir doesn't work.
> Use full path for submodule safe dir

- workflow-templates/knative-releasability.yaml
Default is set in upstream action - https://github.com/knative/actions/pull/108
> default channel is in upstream action

- actions/update-markdown/entrypoint.sh
Markdown task is failing for some reason now - https://github.com/knative-sandbox/knobots/actions/runs/4629224207/jobs/8189236124
I think the way we're writing to the output variable is broken so this changes that.
> fix markdown task

- repos.yaml
eventing-couchdb has not been released since v1.1
> Remove eventing-couchdb

- actions/update-deps/action.yaml
- actions/update-deps/entrypoint.sh
> infer the golang module version from the release version

- .github/workflows/update-nightlies.yaml
PR formatting is broken - https://github.com/knative/serving/pull/13871
I think it's related to switch from using `:set-ouput:` to using `GITHUB_OUTPUT` env var
> fix formatting

- .github/workflows/auto-update-deps.yaml
- actions/update-deps/auto-apply.yaml
We infer this value now so it doesn't need to be an input - see https://github.com/knative-sandbox/knobots/pull/289
> drop module release input

- .github/workflows/update-nightlies.yaml
Doing a proper redirect from stderr to stdout
> my bash is bad

- actions/update-deps/action.yaml
Set  RELEASE: ${{ inputs.release || 'v1.11' }} in actions/update-deps/action.yaml
-
-
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```
> Update RELEASE  to upcoming release version

- README.md
- actions-exclude.yaml
- actions-omitted.yaml
- See `knative/hack` [PR](https://github.com/knative/hack/pull/274#issuecomment-1544938181)
- Includes `knative/hack` repo so it can use GH style actions
- See `knative/hack` [PR](https://github.com/knative/hack/pull/274#issuecomment-1544938181) for more context
> Include knative/hack repo for GH actions

- actions/calculate-matrix/Dockerfile
- actions/update-actions/Dockerfile
- actions/update-deps/Dockerfile
- actions/update-misspell/Dockerfile
- :broom: Update Go version in Dockerfiles to align with rest
/cc @knative-extensions/productivity-wg-leads 
/cc @matejvasek
> Update Go version in Dockerfiles to align with rest

- repos.yaml
- Onboard the repo serving-progressive-rollout.
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```
> Add the repo serving-progressive-rollout

- actions-exclude.yaml
- deps-exclude.yaml
- gofmt-exclude.yaml
- repos.yaml
- Add knative/ux to the knobots automation, specifically for community file sync, markdown checks, and spell checks
Currently, the community files are not being synced to knative/ux, which makes it hard to keep the approvers synced with knative/community
```release-note
Community files are now synced to the UX WG.
```
> Added UX WG to automation

- actions-omitted.yaml
part of https://github.com/knative/infra/issues/207
> Disable autosyncing style and use manual one

- actions/update-deps/entrypoint.sh
- :lady_beetle: Open PR on any change in vendorless projects
/kind bug
Fixes #340
> :lady_beetle: Open PR on any change in vendorless projects

- .github/workflows/update-nightlies.yaml
- 🧹 added net-gateway-api gateway-api.yaml crd file to nightlies
/kind cleanup
Fixes #
```release-note
Now the Kubernetes Gateway API CRDs are included in a separate files in the net-gateway-api nigthly builds
```
> added net-gateway-api gateway-api.yaml crd file to nightlies

- repos.yaml
- Add backstage-plugins repository to automation
-
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```
> Add backstage-plugins repository to automation

- repos.yaml
> Remove eventing-kafka

- repos.yaml
/assign @izabelacg 
Part of https://github.com/knative/serving/issues/14640
> drop machinery for net-http01

- repos.yaml
Part of https://github.com/knative/eventing/issues/7670
> drop machinery for eventing-rabbitmq

- .github/workflows/auto-fork.yaml
- .github/workflows/update-nightlies.yaml
- actions/calculate-matrix/Dockerfile
- actions/update-actions/Dockerfile
- actions/update-deps/Dockerfile
- actions/update-gofmt/Dockerfile
- actions/update-misspell/Dockerfile
> bump go to v1.22

- cmd/gen-actions/actions_template.yaml
Fixes: https://github.com/peter-evans/create-pull-request/issues/2790
> Update create-pull-request actions 

- .github/workflows/update-nightlies.yaml
- Add contour-gateway.yaml file to nightly: net-gateway-api
> Add contour-gateway yaml to nightly

- actions-exclude.yaml
- deps-exclude.yaml
- gofmt-exclude.yaml
- markdown-exclude.yaml
- misspell-exclude.yaml
- repos.yaml
- Add specs to Knative automation, particularly OWNERS_ALIASES automation.
- (See https://github.com/knative/specs/pull/112 for what we want automated)
/kind cleanup
> Add specs repo to knobots

- actions/update-deps/action.yaml
- Update auto-update action version to 1.15
/cc @knative-extensions/knative-release-leads
> Update auto-update action version to 1.15

- workflow-templates/knative-go-test.yaml
- Add codecov token to unit test template
Third time the charm, I guess. Sorry guys, at first I haven't grasped which repo is a source of truth for actions sync. 
/cc @upodroid @cardil
> Add codecov token to unit test template

- repos.yaml
- Similar to https://github.com/knative-extensions/knobots/pull/333
- Needed by https://github.com/knative/community/issues/1527
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```
> Add the repo autoscaler-keda

- actions/update-deps/Dockerfile
- :bug: Set GOTOOLCHAIN=local
/kind bug
Follow up to knative/infra#471
/cc @ReToCode
> :bug: Set GOTOOLCHAIN=local

- actions/update-deps/entrypoint.sh
- Temporary change in order to debug the error in https://github.com/knative-extensions/knobots/actions/runs/10683503406/job/29611769106. Error is silent.
> Enable debugging for update deps action entrypoint script

- .github/workflows/update-nightlies.yaml
Fixes https://github.com/knative-extensions/backstage-plugins/issues/83
> Update Eventing manifest nightlies for Backstage plugins repo

- deps-exclude.yaml
- gofmt-exclude.yaml
- repos.yaml
- Adding func-python to the repo list of automation
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```
> Adding func-python to the repo list of automation

- repos.yaml
Part of: https://github.com/knative/community/pull/1622
/cc @pierDipi 
/cc @knative-extensions/productivity-leads
> Archive eventing-kogito repository

- actions/update-deps/Dockerfile
- Install envsubst in update-deps image
- Reason: https://github.com/knative-extensions/knobots/actions/runs/12865381835/job/35865827468
-
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```
> Install envsubst in update-deps image

- actions/update-deps/action.yaml
- Update next release version to 1.18
/cc @knative-extensions/knative-release-leads
> Update next release version to 1.18

- actions/calculate-matrix/Dockerfile
- actions/update-actions/Dockerfile
- actions/update-deps/Dockerfile
- actions/update-gofmt/Dockerfile
- actions/update-misspell/Dockerfile
/assign @skonto 
/assign @dsimansk
> bump go1.24

- actions/update-deps/entrypoint.sh
SImilar to community updates allow knobot dependency  updates to be auto-merged by prow if all the actions are successful.
/assign @dsimansk @cardil @upodroid
> automerge dep updates
